app <- ShinyDriver$new("../..", loadTimeout = 100000, debug='all') # See: https://github.com/rstudio/shinytest/issues/202
app$snapshotInit("test all fields")

app$uploadFile(load_file = "./starwars.yml") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(new_data_catalog_entry = "modify")
app$setInputs(data_catalog_entry_lab = "test")
app$setInputs(data_catalog_entry_lab = "example")
app$setInputs(data_catalog_entry_lab = "example is")
app$setInputs(data_catalog_entry_lab = "example id")
app$setInputs(add_data_catalog_entry_id = "click")
app$snapshot()
app$setInputs(next_field = "data_catalog_entry_details")
app$setInputs(project_name = "bonobo")
app$setInputs(server_address = "test")
app$setInputs(server_address = "")
app$setInputs(server_address = "/a/b/c")
app$setInputs(add_data_catalog_entry_details = "click")
app$snapshot()
app$setInputs(next_field = "person", wait_=FALSE, values_=FALSE)
app$setInputs(person_name = "a")
app$setInputs(person_institution = "B")
app$setInputs(person_email = "C")
app$setInputs(person_role = "HIWI")
app$setInputs(person_uploader = "Yes")
app$setInputs(add_person = "click")
app$snapshot()
app$setInputs(next_field = "species", wait_=FALSE, values_=FALSE)
app$setInputs(species_eng = "a")
app$setInputs(species_loc = "b")
app$setInputs(species_sci = "c")
app$setInputs(add_spec = "click")
app$snapshot()
app$setInputs(next_field = "dates", wait_=FALSE, values_=FALSE)
app$setInputs(date_date = c("2023-12-14", "2023-12-19"))
app$setInputs(add_date = "click", wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(next_field = "location", wait_=FALSE, values_=FALSE)
app$setInputs(loc_long = 10)
app$setInputs(loc_lat = 12)
app$setInputs(loc_country = "Armenia")
app$setInputs(loc_region = "a")
app$setInputs(loc_city = "bc")
app$setInputs(loc_park = "c")
app$setInputs(loc_field_station = "d")
app$setInputs(add_location = "click", wait_=FALSE, values_=FALSE)
app$snapshot()
app$setInputs(next_field = "data_type_overview", wait_=FALSE, values_=FALSE)
app$setInputs(data_type = "ecological")
app$setInputs(add_type = "click")
app$snapshot()
app$setInputs(next_field = "data_description", wait_=FALSE, values_=FALSE)
app$setInputs(data_desc = "hihi")
app$snapshot()
app$setInputs(add_desc = "click")
app$snapshot()
app$setInputs(next_field = "funding_sources", wait_=FALSE, values_=FALSE)
app$setInputs(fund_src = "hihih")
app$setInputs(add_fund = "click")
app$setInputs(add_fund = "click")
app$setInputs(add_fund = "click")
app$snapshot()
app$setInputs(next_field = "keywords", wait_=FALSE, values_=FALSE)
app$setInputs(keyword = "a, b")
app$setInputs(keyword = "a, b, c")
app$setInputs(add_keyword = "click")
app$snapshot()
app$setInputs(new_data_catalog_entry = "add_custom_entry", wait_=FALSE, values_=FALSE)
app$setInputs(custom_name = "custom")
app$setInputs(custom_name = "custom1")
app$setInputs(custom_content = "the cust")
app$setInputs(add_custom = "click")
app$snapshot()
app$setInputs(new_data_catalog_entry = "load", wait_=FALSE, values_=FALSE)